# Generated by Django 5.2.6 on 2025-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
